name = "mai-l"
main = "src/index.js"
compatibility_date = "2024-07-29"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "2"
database_id = "f5741442-e1d9-4f04-9545-daf238b28660"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "f67cc74352e9404dabc6efc24fd599ed"
